[package]
name = "sha512wasm"
version = "0.1.0"
authors = ["Adam C. Foltzer <acfoltzer@fastly.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
lucet-runtime = { path = "../lib/lucet/lucet-runtime" }

[build-dependencies]
lucetc = { path = "../lib/lucet/lucetc" }